In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
dfx = pd.read_csv('./Dataset/diabetes/Diabetes_XTrain.csv')
dfy = pd.read_csv('./Dataset/diabetes/Diabetes_YTrain.csv')

In [29]:
X = dfx.values
Y = dfy.values
print(X.shape)
print(Y.shape)

(576, 8)
(576, 1)


In [18]:
def distance(p1,p2):
    return (np.sum((p2-p1)**2))**0.5

In [73]:
def knn(X,Y,test,k=17):
    m=X.shape[0]
    d=[]
    for i in range(m):
        dist = distance(X[i],test)
        d.append((dist,Y[i]))
    d = np.array(sorted(d))[:,1]
    d = d[:k]
    t = np.unique(d,return_counts=True)
    idx = np.argmax(t[1])
    pred = int(t[0][idx])
    print(pred)
    return pred
    

In [74]:
test = pd.read_csv('./Dataset/diabetes/Diabetes_XTest.csv')

In [75]:
test = test.values
print(test.shape)
print(test)

(192, 8)
[[0.00e+00 1.80e+02 9.00e+01 ... 3.65e+01 3.14e-01 3.50e+01]
 [2.00e+00 9.30e+01 6.40e+01 ... 3.80e+01 6.74e-01 2.30e+01]
 [2.00e+00 1.14e+02 6.80e+01 ... 2.87e+01 9.20e-02 2.50e+01]
 ...
 [0.00e+00 1.62e+02 7.60e+01 ... 4.96e+01 3.64e-01 2.60e+01]
 [1.20e+01 8.40e+01 7.20e+01 ... 2.97e+01 2.97e-01 4.60e+01]
 [0.00e+00 9.40e+01 0.00e+00 ... 0.00e+00 2.56e-01 2.50e+01]]


In [76]:
m = test.shape[0]
output = []
for i in range(m):
    output.append(knn(X,Y,test[i]))
    

1
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
0
1
1
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
1
1
0
1
0
0
0
1
0
0
1
0
1
0
1
0
1
1
0
1
0
0
1
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
1
1
1
0
1
0
0
0
0
0
1
1
0
0
0
1
0
1
0
0
1
1
1
0
0
1
0
1
0
0
0
0
0
0
1
1
1
0
1
0
1
1
0
0
0
0
1
1
1
0
0
1
0
1
1
0
0
1
1
0
0
0
1
0
0
1
1
1
0
1
1
0
0
0
0
0
0
1
0
0
0
0
0
1
0
0
0
0
1
1
0
0
1
0
1
0
0
0
0
1
0
0


In [77]:
print(output)

[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0]


In [78]:
y =  pd.DataFrame(data=output,columns=["Outcome"]) 
y.to_csv("Diabetes.csv",index = False)